baseurl = "https://SativaDelight.info/"
title = "Sativa Delight"
author = ""
copyright = "Information wants to be free [Stewart Brand, 1984]"
canonifyurls = true
paginate = 3
theme = "newsprint"

[params]

subtitle = "Information On Our Products: SITE UNDERCONSTRUCTION"
